name: Schema Definitions CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - '**/package-lock.json'
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - 'README.md'
      - '**/package-lock.json'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Set $refs and $ids to local values
        run: npm run update:refs -- --environment local

      - name: Run validation tests
        run: npm run test

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Set $refs to remote on merge and update $ids
        if: steps.branch-name.outputs.is_default == 'true' && github.event_name != 'release'
        run: |
          npm run update:refs -- --environment remote --stage true
          npm run update:version --stage true
          npx lint-staged

      # commit definitions with updated $refs

      - name: Add, commit and push updated definitions
        id: commit-definitions
        if: steps.branch-name.outputs.is_default == 'true' && github.event_name != 'release'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update $refs to remote urls [skip ci]'
          file_pattern: '**/*.json'
          commit_options: '--no-verify'
